# Lab 1.2: Example of Value Function

This lab demonstrates a simple state-value representation of a 3x3 GridWorld environment.

### Objectives
- Define a basic GridWorld environment.
- Create a state-value lookup table representation (`ValueFunction`).
- Initialize and update values for states based on immediate environment rewards.

## 1. GridWorld Environment
The gridworld is represented as a 3x3 grid. The cell at index `(2, 1)` (bottom-middle) provides an immediate reward of $+1$, whereas all other cells provide a reward of $0$.

In [1]:
import numpy as np

class GridWorld:
    def __init__(self):
        self.grid_size = (3, 3)
        self.num_actions = 4  # Up, Down, Left, Right
        # Rewards matrix for gridworld cells
        self.rewards = np.array([
            [0, 0, 0],
            [0, 0, 0],
            [0, 1, 0]  # Reward of +1 in bottom-middle cell
        ])

    def get_reward(self, state):
        return self.rewards[state[0], state[1]]

## 2. Value Function Representation
The `ValueFunction` class stores a value matrix of size `(3, 3)` where each element corresponds to the estimated value of the respective grid state.

In [2]:
class ValueFunction:
    def __init__(self, grid_size):
        # Initialize values to 0
        self.values = np.zeros(grid_size)

    def update_value(self, state, new_value):
        self.values[state[0], state[1]] = new_value

    def get_value(self, state):
        return self.values[state[0], state[1]]

## 3. Initialization & Display
We initialize the value function by populating each state with its immediate reward from the gridworld, and print the output matrix.

In [3]:
grid_world = GridWorld()
value_function = ValueFunction(grid_world.grid_size)

# Initialize value function with state rewards
for i in range(grid_world.grid_size[0]):
    for j in range(grid_world.grid_size[1]):
        state = (i, j)
        reward = grid_world.get_reward(state)
        value_function.update_value(state, reward)

print("Initial Value Function:")
print(value_function.values)

Initial Value Function:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 1. 0.]]
